analytics-id:
#Pages
pages:
  - { name: "Episodi", link: "episodes.html" }
  - { name: "About", link: "about.html" }
social:
  - { icon: "instagram", type: "brand", link: "#" }
  #  - { icon: "twitter", type: "brand", link: "#" }
  #  - { icon: "facebook", type: "brand", link: "#" }
  #  - { icon: "youtube", type: "brand", link: "#" }
  - { icon: "envelope", type: "solid", link: "mailto:info@decadi.it" }
  - { icon: "rss", type: "solid", link: "#" }

websites-podcast:
  - { name: "Spotify", link: "#" }
  - { name: "YouTube", link: "#" }
  - { name: "Spreaker", link: "#" }
  - { name: "Google Podcast", link: "#" }

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname:
