analytics-id:
#Pages
pages:
  - { name: "Episodi", link: "episodes" }
  - { name: "About", link: "about" }
social:
  - {
      icon: "instagram",
      type: "brand",
      link: "https://www.instagram.com/decadi.podcast/#",
    }
  #  - { icon: "twitter", type: "brand", link: "#" }
  #  - { icon: "facebook", type: "brand", link: "#" }
  #  - { icon: "youtube", type: "brand", link: "#" }
  - { icon: "envelope", type: "solid", link: "mailto:info@decadi.it" }
  - {
      icon: "rss",
      type: "solid",
      link: "https://anchor.fm/s/d9dfa7f8/podcast/rss",
    }

websites-podcast:
  - {
      name: "Spotify",
      link: "https://open.spotify.com/show/7tc6aio5v6rB5iCeEbAS7e",
    }
  - { name: "Anchor", link: "https://anchor.fm/decadi-millenio-in-mezzo" }
  - {
      name: "Google Podcast",
      link: "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9kOWRmYTdmOC9wb2RjYXN0L3Jzcw",
    }
  - {
      name: "Apple Podcast",
      link: "https://podcasts.apple.com/us/podcast/decadi-|-un-millennio-in-mezzo/id1670688773",
    }
  - {
      name: "Amazon Music",
      link: "https://music.amazon.it/podcasts/8adfc387-da1b-45f9-878d-e46dd00d44e1/decadi-un-millennio-in-mezzo",
    }
